---
# Run in parallel
run_parallel: 1
# Number of workers for Dask
n_workers: 16
# Threads per worker
threads_per_worker: 1
dask_tmp_dir: '/tmp'
# Start/end date and time
startdate: 'STARTDATE.1200'
enddate: 'ENDDATE.0000'
# Ensemble member name
ensmember: 'ENSMEMBER'
# wrfout domain name (d01: 500m, d02: 100m)
domain: 'd02'
# Resolution: 'meso' or 'les'
resolution: 'les'
# Maximum time difference allowed to match the datasets
time_window: 30  # [second]
# Input/output file locations
# Track stats directory
stats_path: '/pscratch/sd/f/feng045/lasso/les/STARTDATE/ENSMEMBER/CONFIG/d4/stats/'
# Track pixel file directory
pixelfile_path: '/pscratch/sd/f/feng045/lasso/les/STARTDATE/ENSMEMBER/CONFIG/d4/celltracking/'
# 3D Met file directory
metfile_path: '/pscratch/sd/f/feng045/lasso/staged_runs/STARTDATE/ENSMEMBER/CONFIG/les/subset_d4/'
cldfile_path: '/pscratch/sd/f/feng045/lasso/staged_runs/STARTDATE/ENSMEMBER/CONFIG/les/subset_d4/'
# Output file directory
output_path: '/pscratch/sd/f/feng045/lasso/les/STARTDATE/ENSMEMBER/CONFIG/d4/stats/'
# File base names
pixel_filebase: 'regrid_celltracks_'
reg_filebase: 'corlasso_methamsl_STARTDATE00ENSMEMBERd4_CONFIG_M1.m1.'
met_filebase: 'corlasso_met_STARTDATE00ENSMEMBERd4_CONFIG_M1.m1.'
cld_filebase: 'corlasso_cld_STARTDATE00ENSMEMBERd4_CONFIG_M1.m1.'
# W thresholds to define cores
W_up_thresh: 2.0  # [m/s]
W_down_thresh: -1.0  # [m/s]
# Minimum pixel count for a core
min_core_npix: 9
# Number of pixel to expand a core to get perimeter
core_expand_dist: 3
# Number of cores to save per cell
ncores_min: 20
# Number of hours prior to initiation to extract environment
nhours: 1
# Set max number of times to keep for each track
# ntimes_max: 40
# Set domain size to extract environment
# Number of grid point in lon/lat dimension [center-nx, center+nx], [center-ny, center+ny]
# nx: 300
# ny: 300
nx: 50
ny: 50
nz: 149
# Sub-sample spatial grid (2: sample every 2 grids)
# sub_x: 20
# sub_y: 20
sub_x: 10
sub_y: 10
# Spatial resolution
DX: 100
DY: 100
# Number of grid point to compute center environment profile [-nx_center, +nx_center], [-ny_center,+ny_center]
nx_center: 1
ny_center: 1
# List of 2D variables to pass through from the 3D file
list_var_pass:
  - 'conv_core'
  - 'conv_mask'
  - 'dbz_comp'
  - 'echotop10'
  - 'LWP'
  - 'IWP'
  - 'PWV'
  - 'T2'
  - 'Q2'
  - 'PSFC'
  - 'U10'
  - 'V10'
  - 'RAINNC'