---
# Run in parallel
run_parallel: 1
# Number of workers for Dask
n_workers: 8
# Threads per worker
threads_per_worker: 1
dask_tmp_dir: '/tmp'
# Start/end date and time
startdate: 'STARTDATE.1200'
enddate: 'ENDDATE.0000'
# Ensemble member name
ensmember: 'ENSMEMBER'
# wrfout domain name (d01: 500m, d02: 100m)
domain: 'd01'
# Resolution: 'meso' or 'les'
resolution: 'les'
# Maximum time difference allowed to match the datasets
time_window: 30  # [second]
# Input/output file locations
# Track stats directory
stats_path: '/gpfs/wolf/atm131/proj-shared/zfeng/cacti/les/STARTDATE/ENSMEMBER/CONFIG/d3/stats/'
# Track pixel file directory
pixelfile_path: '/gpfs/wolf/atm131/proj-shared/zfeng/cacti/les/STARTDATE/ENSMEMBER/CONFIG/d3/celltracking/'
# 3D Met file directory
regfile_path: '/gpfs/wolf/atm131/proj-shared/zfeng/cacti/les/STARTDATE/ENSMEMBER/CONFIG/d3/run/'
metfile_path: '/gpfs/wolf/cli120/world-shared/d3m088/cacti/staged_runs/STARTDATE/ENSMEMBER/CONFIG/les/subset_d3/'
# Raw WRF output file directory
wrfout_path1: '/gpfs/wolf/cli120/proj-shared/sey/cacti/wrf/prod/'
wrfout_path2: '/gpfs/wolf/cli120/proj-shared/d3m088/cacti/production/les/'
# Output file directory
output_path: '/gpfs/wolf/atm131/proj-shared/zfeng/cacti/les/STARTDATE/ENSMEMBER/CONFIG/d3/stats/'
# File base names
pixel_filebase: 'celltracks_'
reg_filebase: 'corlasso.methamsl.STARTDATE00ENSMEMBERd3.CONFIG.M1.m1.'
met_filebase: 'corlasso.met.STARTDATE00ENSMEMBERd3.CONFIG.M1.m1.'
cld_filebase: 'corlasso.cld.STARTDATE00ENSMEMBERd3.CONFIG.M1.m1.'
# W thresholds to define cores
W_up_thresh: 2.0  # [m/s]
W_down_thresh: -1.0  # [m/s]
# Minimum pixel count for a core
min_core_npix: 2
# Number of cores to save per cell
ncores_min: 20
# Number of hours prior to initiation to extract environment
nhours: 1
# Set domain size to extract environment
# Number of grid point in lon/lat dimension [center-nx, center+nx], [center-ny, center+ny]
nx: 60
ny: 60
nz: 149
# Sub-sample spatial grid (2: sample every 2 grids)
sub_x: 2
sub_y: 2
# Spatial resolution
DX: 500
DY: 500
# Number of grid point to compute center environment profile [-nx_center, +nx_center], [-ny_center,+ny_center]
nx_center: 1
ny_center: 1
# Subset boundary [lon_min, lon_max, lat_min, lat_max]
geolimits: [-33.3, -65.9, -30.8, -63.4]
# List of 2D variables to pass through from the 3D file
list_var_pass:
  - 'conv_core'
  - 'conv_mask'
  # - 'tracknumber'
  - 'dbz_comp'
  - 'echotop10'
  - 'LWP'
  - 'IWP'
  - 'PWV'
  - 'T2'
  - 'Q2'
  - 'PSFC'
  - 'U10'
  - 'V10'
  - 'RAINNC'