---
# Run in parallel
run_parallel: 1
# Number of workers for Dask
# n_workers: 8 # For hi-mem corestats
# n_workers: 8 # For hi-mem env3d
n_workers: 8 # For 3d environment output
# n_workers: 12 # For plotting
# n_workers: 5
# Threads per worker
threads_per_worker: 1
dask_tmp_dir: '/tmp'
# Start/end date and time
startdate: '20190129.1500'
enddate: '20190129.1800'
# Ensemble member name
ensmember: 'eda09'
# wrfout domain name (d01: 500m, d02: 100m)
domain: 'd02'
# Resolution: 'meso' or 'les'
resolution: 'les'
# Maximum time difference allowed to match the datasets
time_window: 5  # [second]
# Input/output file locations
# Track stats directory
# stats_path: '/gpfs/wolf/atm131/proj-shared/enochjo/20190129_eda09_tracks_60s/stats/'
stats_path: '/gpfs/wolf/atm131/proj-shared/enochjo/20190129_eda09_tracks/stats/'
# Track pixel file directory
# pixelfile_path: '/gpfs/wolf/atm131/proj-shared/enochjo/20190129_eda09_tracks_60s/celltracking/'
# pixelfile_path_tmp: '/gpfs/wolf/atm131/proj-shared/enochjo/20190129_eda09_tracks/celltracking/'
pixelfile_path: '/gpfs/wolf/atm131/proj-shared/enochjo/20190129_eda09_tracks/celltracking/'
# 3D Met file directory
metfile_path: '/gpfs/wolf/atm131/proj-shared/enochjo/20190129_eda09_interp/'
# 3D Ent file directory EJ
entfile_path: '/gpfs/wolf/atm131/proj-shared/enochjo/20190129_eda09_entrain/'
# Raw WRF output file directory
wrfout_path1: '/gpfs/wolf/cli120/proj-shared/sey/cacti/wrf/prod/'
wrfout_path2: '/gpfs/wolf/cli120/proj-shared/d3m088/cacti/production/les/'
# Output file directory
# output_path: '/gpfs/wolf/atm131/proj-shared/enochjo/20190129_eda09_tracks_60s/stats/'
output_path: '/gpfs/wolf/atm131/proj-shared/enochjo/20190129_eda09_tracks/stats/'
# File base names
pixel_filebase: 'regrid_celltracks_'
met_filebase: 'corlasso.cldhamsl.2019012900eda09d4.base.M1.m1.'
#(EJ)
ent_filebase: 'entdvdt.cldhamsl.2019012900eda09d4.base.M1.m1.' 
# ent_filebase: 'entrain.cldhamsl.2019012900eda09d4.base.M1.m1.' 
cld_filebase: 'corlasso.cldhamsl.STARTDATE00ENSMEMBERd4.base.M1.m1.'
# W thresholds to define cores
W_up_thresh: 2.0  # [m/s]
W_down_thresh: -1.0  # [m/s]
# Hydrometeor thresholds to define moist updrafts (EJ)
Q_up_thresh: 0.00001 # 0.01/1000  # [kg/kg]
Q_down_thresh: 0.00005 # 0.05/1000  # [kg/kg]
# Minimum pixel count for a core
min_core_npix: 9
# Number of cores to save per cell
ncores_min: 35
# Number of hours prior to initiation to extract environment
nhours: 1 # Not used anymore in env3d
nminutes: 60
# Set max number of times to keep for each track
# ntimes_max: 40
# Set domain size to extract environment
# Number of grid point in lon/lat dimension [center-nx, center+nx], [center-ny, center+ny]
nx: 100
ny: 100
# Sub-sample spatial grid (2: sample every 2 grids)
sub_x: 1
sub_y: 1


# radii_expand: [1,2,3,4,5]