"""
Loop over LASSO runs to make quicklook plots and animations.

Note: requires PyFLEXTRKR cell tracking config files for each LASSO case.
The config files are generated by:
pyflex_config/slurm/make_lasso_config_slurm_scripts_cu2.sh
"""
import subprocess
import sys
import os

if __name__ == "__main__":

    # Specify resolution: 'les' or 'meso'
    # resolution = 'meso'
    resolution = 'les'
    # Specify configuration: 'base' or 'morr'
    configuration = 'base'
    # Specify domain
    # domain = 'd2'
    # domain = 'd3'
    # domain = 'd4_5min'
    # domain = 'd2_15min'
    # domain = 'd3_15min'
    domain = 'd4_15min'

    # Flag to call Python codes to make plots
    make_plots = True
    make_mp4 = True

    # Base config (Thompson)
    if configuration == 'base':
        # start_dates = ["20190123", "20181129"]
        # ens_members = ["gefs18", "gefs09"]
        # start_dates = ["20190123"]
        # ens_members = ["gefs18"]
        start_dates = [
            "20181129", "20181129", "20181129", "20181129",
            "20181204", "20181204", 
            "20181205", 
            "20181219", 
            "20190122", "20190122",
            "20190123", "20190123",
            "20190125", "20190125",
            "20190129", "20190129",
            "20190208", "20190208",
        ]
        ens_members = [
            "gefs00", "gefs03", "gefs09", "gefs18",
            "gefs18", "gefs19",
            "gefs01", 
            "eda09", 
            "gefs01", "gefs18",
            "eda05", "gefs18",
            "eda07", "gefs11",
            "eda09", "gefs11",
            "eda03", "eda08",
        ]

    # Morrison
    elif configuration == 'morr':
        start_dates=[
            "20181204", "20181204", "20181204",
            "20181205", "20181205", "20181205",
            "20181219", "20181219", "20181219",
            "20190122", "20190122",
            "20190123", "20190123",
            "20190125",
            "20190129", "20190129",
            "20190208",
        ]
        ens_members=[
            "gefs04", "gefs16", "gefs18",
            "gefs01", "gefs02", "era5",
            "eda09", "gefs10", "gefs11",
            "eda00", "gefs18",
            "eda05", "eda07",
            "eda07",
            "gefs11", "eda09",
            "eda03",
        ]
    # else:
    #     sys.exit('Unknown resolution!')

    # Plotting code name
    code_name = '/ccsopen/home/zhe1feng1/program/lasso/cellgrowth/src/plot_subset_cell_tracks_ETH_terrain.py'
    # Tracking config base name
    config_basename = '/ccsopen/home/zhe1feng1/program/lasso/cellgrowth/tracking/slurm/config_lasso_'
    # Plotting output directory
    # out_dir_root = f'/gpfs/wolf2/arm/atm131/proj-shared/zfeng/cacti/{resolution}/quicklooks_trackpaths_terrain_5min/'
    out_dir_root = f'/gpfs/wolf2/arm/atm131/proj-shared/zfeng/cacti/{resolution}/quicklooks_trackpaths_terrain/'
    # out_dir_root = f'/gpfs/wolf2/arm/atm131/proj-shared/zfeng/cacti/{resolution}/quicklooks_trackpaths_ETH/'
    # out_dir_root = f'/gpfs/wolf2/arm/atm131/proj-shared/zfeng/cacti/{resolution}/quicklooks_trackpaths_ETH_terrain/'

    # Output animation directory
    out_dir_mp4 = f'{out_dir_root}animation/{configuration}/'
    os.makedirs(out_dir_mp4, exist_ok=True)

    # figbasename = f'{domain}_eth10dbz_'
    figbasename = f'{domain}_dbz_comp_'
    figsize = [8,7]
    extent = [-65.9, -63.6, -33.1, -31.15]
    radar_lon, radar_lat = -64.7284, -32.1264
    vfscale = '1200:-1'
    parallel = 1

    # Determine framerate based on domain
    if (domain == 'd4') | (domain == 'd3') | (domain == 'd2') | (domain == 'd4_5min') | (domain == 'd3_5min') | (domain == 'd2_5min'):
        framerate = 6  # for 5min
    elif (domain == 'd4_15min') | (domain == 'd3_15min') | (domain == 'd2_15min'):
        framerate = 2  # for 15min

    # Gridspacing
    if ('d2' in domain): gridspacing = 'wrf2.5km'
    if ('d3' in domain): gridspacing = 'wrf500m'
    if ('d4' in domain): gridspacing = 'wrf100m'

    # Set title suffix based on domain
    if 'd2' in domain:
        title_suffix = '(LASSO 2.5 km)'
    elif 'd3' in domain:
        title_suffix = '(LASSO 500 m)'
    elif 'd4' in domain:
        title_suffix = '(LASSO 100 m)'
    else:
        title_suffix = ''

    # Loop over each case date
    for ii in range(0, len(start_dates)):
        idate = start_dates[ii]
        imember = ens_members[ii]
        year = idate[0:4]
        month = idate[4:6]
        day = idate[6:8]
        sdate = f'{year}-{month}-{day}T12:00'
        edate = f'{year}-{month}-{day}T23:55'
        config = f'{config_basename}{gridspacing}_{idate}_{imember}_{configuration}.yml'
        out_dir = f'{out_dir_root}/{idate}/{imember}/{configuration}/{domain}/'
        # Make quicklook plots
        cmd = f"python {code_name} -s {sdate} -e {edate} -c {config} -p {parallel} --radar_lat {radar_lat} --radar_lon {radar_lon} --title_suffix '{title_suffix}' " + \
              f"--output {out_dir} --figbasename {figbasename} --figsize {figsize[0]} {figsize[1]} --extent {extent[0]} {extent[1]} {extent[2]} {extent[3]}"
        # import pdb; pdb.set_trace()
        if make_plots == True:
            print(cmd)
            subprocess.run(cmd, shell=True)

        # Make animation
        # video_filename = f'{out_dir_mp4}{figbasename}{idate}_{imember}_{domain}.mp4'
        video_filename = f'{out_dir_mp4}{figbasename}{idate}_{imember}.mp4'
        # Make ffmpeg command
        cmd = f"ffmpeg -framerate {framerate} -pattern_type glob -i '{out_dir}{figbasename}*.png' -c:v libx264 -r 10 -crf 20 -pix_fmt yuv420p -vf scale={vfscale} -y {video_filename}"
        # print(cmd)
        if make_mp4 == True:
            print(video_filename)
            subprocess.run(cmd, shell=True)

        
    