"""
Loop over LASSO runs to make cold pool animations.

Note: requires existing cold pool snapshots.
Cold pool snapshots are generated by:
- make_slurm_plot_lasso_coldpool_snapshots.py
- plot_subset_cell_tracks_coldpool_animation.py
"""
import subprocess
import textwrap
import os

if __name__ == "__main__":

    # Specify resolution: 'les' or 'meso'
    resolution = 'meso'
    # resolution = 'les'
    # Specify configuration: 'base' or 'morr'
    configuration = 'base'
    # Specify domain
    # domain = 'd2'
    # domain = 'd3'
    # domain = 'd4'
    domain = 'd2_15min'
    # domain = 'd3_15min'
    # domain = 'd4_15min'

    # Submit slurm job
    # submit_job = True

    # Flag to call Python codes to make plots
    # make_plots = True
    make_mp4 = True

    # Base config (Thompson)
    if configuration == 'base':
        # start_dates = ["20190129"]
        # ens_members = ["eda09"]
        # start_dates = ["20190208"]
        # ens_members = ["eda08"]
        start_dates = [
            "20181129", "20181129", "20181129", "20181129",
            "20181204", "20181204", 
            "20181205", 
            "20181219", 
            "20190122", "20190122",
            "20190123", "20190123",
            "20190125", "20190125",
            "20190129", "20190129",
            "20190208", "20190208",
        ]
        ens_members = [
            "gefs00", "gefs03", "gefs09", "gefs18",
            "gefs18", "gefs19",
            "gefs01", 
            "eda09", 
            "gefs01", "gefs18",
            "eda05", "gefs18",
            "eda07", "gefs11",
            "eda09", "gefs11",
            "eda03", "eda08",
        ]

    # Morrison
    elif configuration == 'morr':
        start_dates=[
            "20181204", "20181204", "20181204",
            "20181205", "20181205", "20181205",
            "20181219", "20181219", "20181219",
            "20190122", "20190122",
            "20190123", "20190123",
            "20190125",
            "20190129", "20190129",
            "20190208",
        ]
        ens_members=[
            "gefs04", "gefs16", "gefs18",
            "gefs01", "gefs02", "era5",
            "eda09", "gefs10", "gefs11",
            "eda00", "gefs18",
            "eda05", "eda07",
            "eda07",
            "gefs11", "eda09",
            "eda03",
        ]
    # else:
    #     sys.exit('Unknown resolution!')

    # Plotting code name
    code_name = '/ccsopen/home/zhe1feng1/program/lasso/cellgrowth/src/plot_subset_cell_tracks_coldpool_animation.py'
    # Tracking config base name
    config_basename = '/ccsopen/home/zhe1feng1/program/pyflex_config/config/config_lasso_'
    slurm_basename = 'slurm.submit_coldpool_'
    # Plotting output directory
    out_dir_root = f'/gpfs/wolf2/arm/atm131/proj-shared/zfeng/cacti/{resolution}/quicklooks_coldpool/'

    # Output animation directory
    out_dir_mp4 = f'{out_dir_root}animation/{configuration}/'
    os.makedirs(out_dir_mp4, exist_ok=True)

    figbasename = 'coldpool_'
    figsize = [10,10]
    extent = [-65.9, -63.4, -33.3, -30.8]
    vfscale = '1200:-1'
    parallel = 1

    # Determine framerate based on domain
    if (domain == 'd4') | (domain == 'd3') | (domain == 'd2'):
        framerate = 6  # for 5min
    elif (domain == 'd4_15min') | (domain == 'd3_15min') | (domain == 'd2_15min'):
        framerate = 2  # for 15min

    # Gridspacing
    if ('d2' in domain): gridspacing = 'wrf2.5km'
    if ('d3' in domain): gridspacing = 'wrf500m'
    if ('d4' in domain): gridspacing = 'wrf100m'

    # Loop over each case date
    for ii in range(0, len(start_dates)):
        idate = start_dates[ii]
        imember = ens_members[ii]
        year = idate[0:4]
        month = idate[4:6]
        day = idate[6:8]
        sdate = f'{year}-{month}-{day}T12:00'
        edate = f'{year}-{month}-{day}T23:55'
        config = f'{config_basename}{gridspacing}_{idate}_{imember}_{configuration}.yml'
        out_dir = f'{out_dir_root}/{idate}/{imember}/{configuration}/{domain}/'
        # # Make quicklook plots
        # cmd = f'python {code_name} -s {sdate} -e {edate} -c {config} -p {parallel} ' + \
        #       f'--output {out_dir} --figbasename {figbasename} --figsize {figsize[0]} {figsize[1]} --extent {extent[0]} {extent[1]} {extent[2]} {extent[3]}'
        # task_file.write(f"{cmd}\n")
        # ntasks += 1

        # Make animation
        video_filename = f'{out_dir_mp4}{figbasename}{idate}_{imember}_{domain}.mp4'
        # Make ffmpeg command
        cmd = f"ffmpeg -framerate {framerate} -pattern_type glob -i '{out_dir}{figbasename}*.png' -c:v libx264 -r 10 -crf 20 -pix_fmt yuv420p -vf scale={vfscale} -y {video_filename}"
        print(cmd)
        if make_mp4 == True:
            subprocess.run(cmd, shell=True)
            print(video_filename)

    